### ISSUE TITLE
 [vite] Internal server error: Failed to resolve entry for package "xxx/nx-recipes/standalone-react-app/cart". The package may have incorrect main/module/exports specified in its package.json.

### ISSUE THREAD

**Issue by sunny15100** [nrwl/nx-recipes#14]
### the problem of ”standalone react app":
I input the url "http://localhost:4200/cart",  then click the chrome's refresh button, then error  " [vite] Internal server error: Failed to resolve entry for package "/Users/sxj/Desktop/self-learning/nx-recipes/standalone-react-app/cart". The package may have incorrect main/module/exports specified in its package.json." will happen.

The error detail:
`4:19:56 PM [vite] Internal server error: Failed to resolve entry for package "/Users/sxj/Desktop/self-learning/nx-recipes/standalone-react-app/cart". The package may have incorrect main/module/exports specified in its package.json.
      at packageEntryFailure (file:///Users/sxj/Desktop/self-learning/nx-recipes/standalone-react-app/node_modules/_vite@3.2.5@vite/dist/node/chunks/dep-5605cfa4.js:34107:11)
      at resolvePackageEntry (file:///Users/sxj/Desktop/self-learning/nx-recipes/standalone-react-app/node_modules/_vite@3.2.5@vite/dist/node/chunks/dep-5605cfa4.js:34104:5)
      at tryResolveFile (file:///Users/sxj/Desktop/self-learning/nx-recipes/standalone-react-app/node_modules/_vite@3.2.5@vite/dist/node/chunks/dep-5605cfa4.js:33717:38)
      at tryFsResolve (file:///Users/sxj/Desktop/self-learning/nx-recipes/standalone-react-app/node_modules/_vite@3.2.5@vite/dist/node/chunks/dep-5605cfa4.js:33699:16)
      at Context.resolveId (file:///Users/sxj/Desktop/self-learning/nx-recipes/standalone-react-app/node_modules/_vite@3.2.5@vite/dist/node/chunks/dep-5605cfa4.js:33516:28)
      at Object.resolveId (file:///Users/sxj/Desktop/self-learning/nx-recipes/standalone-react-app/node_modules/_vite@3.2.5@vite/dist/node/chunks/dep-5605cfa4.js:40462:46)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async ModuleGraph.resolveUrl (file:///Users/sxj/Desktop/self-learning/nx-recipes/standalone-react-app/node_modules/_vite@3.2.5@vite/dist/node/chunks/dep-5605cfa4.js:60809:26)
      at async ModuleGraph.getModuleByUrl (file:///Users/sxj/Desktop/self-learning/nx-recipes/standalone-react-app/node_modules/_vite@3.2.5@vite/dist/node/chunks/dep-5605cfa4.js:60681:23)
      at async doTransform (file:///Users/sxj/Desktop/self-learning/nx-recipes/standalone-react-app/node_modules/_vite@3.2.5@vite/dist/node/chunks/dep-5605cfa4.js:36831:20)
`
![截屏2023-01-15 下午4 36 02](https://user-images.githubusercontent.com/17845065/212531178-1d205459-b959-4cc5-be31-28d27a685170.png)

I input the url "http://localhost:4200", then click the "View Cart" link, the error will not happen. why?
<img width="1293" alt="截屏2023-01-15 下午4 29 50" src="https://user-images.githubusercontent.com/17845065/212531096-2091f203-8057-4fd5-89ad-c0ef0057f884.png">

**Comment by ZackDeRose** [comment]
I'll take a look at this tomorrow. Thanks for the report!

**Comment by sunny15100** [comment]
thank you！
